version: '2.1'
orbs:
  docker: circleci/docker@2.1.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - build:
          context: twitter_clone_creds
      - docker/publish:
          image: sanchitbansal10/twitter_clone
          tag: eureka_server
